# Generated by Django 5.2.14 on 2026-05-25 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plugin_mi_depafi.realisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisation_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('realisation', 'user')},
            },
        ),
    ]
