# Generated by Django 5.2.14 on 2026-05-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0003_realisationnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisationnode',
            options={'verbose_name': 'Nœud réalisation'},
        ),
    ]
