# Generated by Django 5.2.15 on 2026-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0004_alter_realisationnode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site ou bâtiment concerné'),
        ),
    ]
