# Generated by Django 5.2.15 on 2026-06-29 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0004_alter_realisationnode_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
    ]
