# Generated by Django 5.2.15 on 2026-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0007_realisation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='key_figures',
            field=models.TextField(blank=True, verbose_name='Chiffres clés'),
        ),
    ]
