# Generated by Django 5.2.15 on 2026-07-01 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plugin_mi_depafi", "0008_realisationdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="realisation",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realisation_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
