# Generated by Django 5.2.15 on 2026-06-30 08:58

import django.db.models.deletion
import plugin_mi_depafi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mi_depafi', '0008_realisation_key_figures'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=plugin_mi_depafi.models._realisation_document_upload_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='plugin_mi_depafi.realisation')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
